/*
  Generate Arabic multiple-choice questions seed SQL
  Usage: node scripts/generate_questions.js
  This writes supabase/seeds/questions_seed.sql
*/
const fs = require('fs');
const path = require('path');

const outPath = path.join(__dirname, '..', 'supabase', 'seeds', 'questions_seed.sql');
const difficulties = [
  { key: 'easy', points: 20 },
  { key: 'medium', points: 30 },
  { key: 'hard', points: 40 },
  { key: 'legendary', points: 50 }
];
const totalPer = 160;

// Simple pools to create varied Arabic questions
const topics = [
  'الرياضيات', 'التاريخ', 'الجغرافيا', 'العلوم', 'الثقافة العامة', 'اللغة العربية', 'الرياضة', 'الفنون', 'الاختراعات', 'الطبيعة'
];

function randomChoice(arr) { return arr[Math.floor(Math.random()*arr.length)]; }
function escapeSql(s){ return s.replace(/'/g, "''"); }

let inserts = [];

let qcount = 0;
for(const diff of difficulties){
  for(let i=1;i<=totalPer;i++){
    qcount++;
    const topic = topics[(qcount-1) % topics.length];
    const base = `${topic} سؤال ${i} (${diff.key})`;
    // Create a simple question template in Arabic
    const question = `${base}: ما الإجابة الصحيحة للاختيار التالي؟`;
    // Generate 4 choices with one correct (index 0..3)
    const correctIdx = Math.floor(Math.random()*4);
    const choices = [];
    for(let c=0;c<4;c++){
      if(c===correctIdx){
        choices.push(`${base} - الجواب الصحيح`);
      } else {
        choices.push(`${base} - خيار ${c+1}`);
      }
    }
    const choicesJson = JSON.stringify(choices, null, 0);
    const insert = `INSERT INTO question_bank (id, question_text, choices, correct_choice, difficulty, points, metadata) VALUES (gen_random_uuid(), '${escapeSql(question)}', '${escapeSql(choicesJson)}'::jsonb, ${correctIdx}, '${diff.key}', ${diff.points}, '{}'::jsonb);`;
    inserts.push(insert);
  }
}

const header = `-- Questions seed generated by scripts/generate_questions.js\n-- Total questions: ${qcount}\n\n`;
fs.writeFileSync(outPath, header + inserts.join('\n') + '\n', 'utf8');
console.log('Wrote', outPath, 'with', qcount, 'questions');
